#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ReproduceProblem.Resource", IsApplication=true)]

namespace ReproduceProblem
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int androidcolors = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040007
			public const int Background = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int BackgroundContrast = 2130968584;
			
			// aapt resource value: 0x7f040002
			public const int ButtonBackground = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int DkGray = 2130968579;
			
			// aapt resource value: 0x7f040005
			public const int ListItemBackground = 2130968581;
			
			// aapt resource value: 0x7f040004
			public const int ListItemBackgroundActive = 2130968580;
			
			// aapt resource value: 0x7f040006
			public const int ListItemText = 2130968582;
			
			// aapt resource value: 0x7f040001
			public const int TextBackground = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int TextBackgroundTint = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Checkmark = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Clock = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Delete = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int Icon = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int textarea_back = 2130837508;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070005
			public const int ActivityChangeShowNameField = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int ActivityChangeShowTextField = 2131165190;
			
			// aapt resource value: 0x7f070002
			public const int ActivityEditDateField = 2131165186;
			
			// aapt resource value: 0x7f07000d
			public const int ActivityEditTimeField = 2131165197;
			
			// aapt resource value: 0x7f070009
			public const int ButtonDelete = 2131165193;
			
			// aapt resource value: 0x7f07000b
			public const int ButtonSaveEdit = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int ButtonSetReminder = 2131165194;
			
			// aapt resource value: 0x7f070007
			public const int ButtonsWrapper = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int ChangeReminderDateTime = 2131165192;
			
			// aapt resource value: 0x7f07000e
			public const int DialogButtonEnd = 2131165198;
			
			// aapt resource value: 0x7f070003
			public const int DialogButtonNext = 2131165187;
			
			// aapt resource value: 0x7f070001
			public const int DialogDateHelper = 2131165185;
			
			// aapt resource value: 0x7f07000c
			public const int DialogTimeHelper = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int ReallySurelyAButton = 2131165199;
			
			// aapt resource value: 0x7f070004
			public const int fragmentOneMainLayout = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int fragmentThreeMainLayout = 2131165184;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_date_dialog = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fragment_edit = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_time_dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f06000c
			public const int ActivityDateFieldHint = 2131099660;
			
			// aapt resource value: 0x7f06000a
			public const int ActivityNameFieldHint = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int ActivityTextFieldHint = 2131099659;
			
			// aapt resource value: 0x7f060001
			public const int ApplicationName = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int ButtonText = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int DialogDateText = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int DialogTimeText = 2131099657;
			
			// aapt resource value: 0x7f060004
			public const int FirstStepText = 2131099652;
			
			// aapt resource value: 0x7f060007
			public const int FourthStepText = 2131099655;
			
			// aapt resource value: 0x7f060000
			public const int Hello = 2131099648;
			
			// aapt resource value: 0x7f060005
			public const int SecondStepText = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int TaskFirstStepText = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int ThirdStepText = 2131099654;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
